-- Enable Row-Level Security on all Prisma application tables
ALTER TABLE IF EXISTS "Agent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Problem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Solution" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Migration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Verification" ENABLE ROW LEVEL SECURITY;

-- Protect Prisma's internal tracking table as well
ALTER TABLE IF EXISTS "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
